### ISSUE TITLE
[v1.5.2] error: reference to ‘array’ is ambiguous

### ISSUE THREAD

**Issue by voidus** [FairCoinTeam/fair-coin#14] opened 2016-05-24 15:41 UTC
```
net.cpp:64:1: error: reference to ‘array’ is ambiguous
 array<int, THREAD_MAX> vnThreadsRunning;
 ^~~~~
In file included from net.h:9:0,
                 from net.cpp:8:
/usr/include/boost/array.hpp:60:11: note: candidates are: template<class T, long unsigned int N> class boost::array
     class array {
           ^~~~~
In file included from /usr/include/c++/6.1.1/tuple:39:0,
                 from /usr/include/c++/6.1.1/functional:55,
                 from /usr/include/boost/system/error_code.hpp:22,
                 from /usr/include/boost/system/system_error.hpp:14,
                 from /usr/include/boost/thread/exceptions.hpp:22,
                 from /usr/include/boost/thread/pthread/mutex.hpp:14,
                 from /usr/include/boost/thread/mutex.hpp:16,
                 from sync.h:8,
                 from db.h:8,
                 from net.cpp:7:
/usr/include/c++/6.1.1/array:90:12: note:                 template<class _Tp, long unsigned int _Nm> struct_ std::array
     struct array
            ^~~~~
```
Changing net.cpp:61 to `boost::array<int, THREAD_MAX> vnThreadsRunning;` fixes this, which leads me to
```
/usr/bin/ld: qt/libbitcoinqt.a(qt_libbitcoinqt_a-qtipcserver.o): undefined reference to symbol 'shm_unlink@@GLIBC_2.2.5'
```
I'm using arch linux.

**Comment by thokon00** [comment] 2016-05-24 16:46
Try to prefic configure with the rt lib:
```LIBS=-lrt ./configure --with-incompatible-bdb --disable-tests```

BTW, what version of boost are you using? What version of arch linux?

**Comment by voidus** [comment] 2016-05-24 16:48
Sorry about the second error, that was actually me not reading the docs. I'm on arch linux testing.

The problem with the ambiguous reference still stands, though.

**Comment by thokon00** [comment] 2016-05-24 18:17
What version of the boost library are you using?

**Comment by voidus** [comment] 2016-05-24 18:41
I'm using boost version 1.60.0

**Comment by emvigo** [comment] 2016-05-24 21:15
I can confirm this bug. This looks like there has been some API change in Boost.

**Comment by thokon00** [comment] 2016-05-25 08:18
Thanks, @voidus. Fixed now. (761475d)

**Closed by thokon00** 2016-05-25 08:18 UTC

**Comment by emvigo** [comment] 2016-05-28 15:00
Sorry to bring this back to life, but IMO a bugfix like this, that solves a compile issue, should be delivered as a new revision release (1.5.2.1?)... unless you want packagers to backport the fix as a patch... or that you want us to grab the commit, but that surely goes against the packaging standards of almost every sane mantainer.

**Comment by thokon00** [comment] 2016-07-15 13:53
@emvigo FairCoin2 is under heavy development and will replace FairCoin1.x in the near future, so it would not be worth the effort to create a new release for 'just' a compile bug.

Are you a package maintainer of some distribution? Help would be very appreciated!
